package input

import "github.com/vulkan-go/glfw/v3.3/glfw"

// Key maps to an integer value of a keyboard key (glfw values)
type Key int

const (
	KeyEscape       = Key(glfw.KeyEscape)
	KeyF1           = Key(glfw.KeyF1)
	KeyF2           = Key(glfw.KeyF2)
	KeyF3           = Key(glfw.KeyF3)
	KeyF4           = Key(glfw.KeyF4)
	KeyF5           = Key(glfw.KeyF5)
	KeyF6           = Key(glfw.KeyF6)
	KeyF7           = Key(glfw.KeyF7)
	KeyF8           = Key(glfw.KeyF8)
	KeyF9           = Key(glfw.KeyF9)
	KeyF10          = Key(glfw.KeyF10)
	KeyF11          = Key(glfw.KeyF12)
	Key1            = Key(glfw.Key1)
	Key2            = Key(glfw.Key2)
	Key3            = Key(glfw.Key3)
	Key4            = Key(glfw.Key4)
	Key5            = Key(glfw.Key5)
	Key6            = Key(glfw.Key6)
	Key7            = Key(glfw.Key7)
	Key8            = Key(glfw.Key8)
	Key9            = Key(glfw.Key9)
	Key0            = Key(glfw.Key0)
	KeyMinus        = Key(glfw.KeyMinus)
	KeyEqual        = Key(glfw.KeyEqual)
	KeyBackspace    = Key(glfw.KeyBackspace)
	KeyTab          = Key(glfw.KeyTab)
	KeyQ            = Key(glfw.KeyQ)
	KeyW            = Key(glfw.KeyW)
	KeyE            = Key(glfw.KeyE)
	KeyR            = Key(glfw.KeyR)
	KeyT            = Key(glfw.KeyT)
	KeyY            = Key(glfw.KeyY)
	KeyU            = Key(glfw.KeyU)
	KeyI            = Key(glfw.KeyI)
	KeyO            = Key(glfw.KeyO)
	KeyP            = Key(glfw.KeyP)
	KeyLeftBracket  = Key(glfw.KeyLeftBracket)
	KeyRightBracket = Key(glfw.KeyRightBracket)
	KeyBackslash    = Key(glfw.KeyBackslash)
	KeyCapsLock     = Key(glfw.KeyCapsLock)
	KeyA            = Key(glfw.KeyA)
	KeyS            = Key(glfw.KeyS)
	KeyD            = Key(glfw.KeyD)
	KeyF            = Key(glfw.KeyF)
	KeyG            = Key(glfw.KeyG)
	KeyH            = Key(glfw.KeyH)
	KeyJ            = Key(glfw.KeyJ)
	KeyK            = Key(glfw.KeyK)
	KeyL            = Key(glfw.KeyL)
	KeySemiColon    = Key(glfw.KeySemicolon)
	KeyApostrophe   = Key(glfw.KeyApostrophe)
	KeyEnter        = Key(glfw.KeyEnter)
	KeyLeftShift    = Key(glfw.KeyLeftShift)
	KeyZ            = Key(glfw.KeyZ)
	KeyX            = Key(glfw.KeyX)
	KeyC            = Key(glfw.KeyC)
	KeyV            = Key(glfw.KeyV)
	KeyB            = Key(glfw.KeyB)
	KeyN            = Key(glfw.KeyN)
	KeyM            = Key(glfw.KeyM)
	KeyComma        = Key(glfw.KeyComma)
	KeyPeriod       = Key(glfw.KeyPeriod)
	KeySlash        = Key(glfw.KeySlash)
	KeyRightShift   = Key(glfw.KeyRightShift)
	KeyLeftCtrl     = Key(glfw.KeyLeftControl)
	KeyLeftAlt      = Key(glfw.KeyLeftAlt)
	KeySpace        = Key(glfw.KeySpace)
	KeyRightAlt     = Key(glfw.KeyRightAlt)
	KeyRightCtrl    = Key(glfw.KeyRightControl)
	KeyDelete       = Key(glfw.KeyDelete)
	KeyInsert       = Key(glfw.KeyInsert)
	KeyUp           = Key(glfw.KeyUp)
	KeyLeft         = Key(glfw.KeyLeft)
	KeyDown         = Key(glfw.KeyDown)
	KeyRight        = Key(glfw.KeyRight)
)
